name: Sync Hugging Face hub
on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
#       - uses: actions/checkout@v3
#         with:
#           fetch-depth: 0
      - name: Clone from hub
        run: |
          git clone https://huggingface.co/spaces/tumuyan/RealSR
          
      - name: 安装 Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: 安装模块
        run: |
          pip install -r ./RealSR/requirements.txt
          
      - name: 下载文件
        run: python -c 'import RealSR.utils as u; u.dlFile(False, "./RealSR/")'
          
      - name: 列出文件
        run: tree
        
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: cd RealSR && git push https://tumuyan:$HF_TOKEN@huggingface.co/spaces/tumuyan/RealSR
