name: Build libs for hub
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      upload:
        description: 'Upload'
        required: false
        default: yes
        type: choice
        options:
          - 'yes'
          - 'no'
jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
#       - name: Clone from hub
#         run: |
#           git clone https://huggingface.co/spaces/tumuyan/RealSR
          
      - name: Install Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Download glibc
        run: |
          wget http://mirrors.nju.edu.cn/gnu/libc/glibc-2.30.tar.xz
          xz -d glibc-2.30.tar.xz
          tar -xf glibc-2.30.tar

      - name: Build glibc
        run: |
          mkdir build
          ls
          cd build
          ../configure  --prefix=$HOME/local
          make
          make install

      - name: Build glibc
        run: |
          ls
          strings /glibc-2.30/build/math/libm.so.6 | grep GLIBC_

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: glibc.zip
          path: /glibc-2.30/build
          # keep 90 days
          retention-days: 90
#       - name: Push to hub
#         if: (github.event.inputs.upload == 'yes')
#         env:
#           HF_TOKEN: ${{ secrets.HF_TOKEN }}
#         run: |
#           git config --global user.email "tumuyan@gmail.com"
#           git config --global user.name "tumuyan"
#           cd RealSR && git add . && git status -s &&  git commit -m 'github ci' && git push https://tumuyan:$HF_TOKEN@huggingface.co/spaces/tumuyan/RealSR
